- name: "install node exporter."
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/node_exporter-0.17.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    mode: '0777'
    
- name: "add node exporter configuration."
  become: true
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/

- name: "enable node_exporter service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: node_exporter
    enabled: yes
    
---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

 - name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: install pm2
  command: npm install pm2 -g


- name: "Creates backend app directory"
  file:
    path: ~/backend
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: dist.zip
    dest: "~/backend/artifact.tar.gz"

- name: "Unzip backend files"
  unarchive:
    src: "~/backend/artifact.tar.gz"
    dest: "~/backend"
    remote_src: yes

- name: "Install dependencies for project"
  shell: |
    cd ~/backend
    npm install

- name: "Executing node"
  shell: |
    export
    cd ~/backend
    pm2 start main.js
  register: execute_node

- name:  start app
  command: |
   args:
      chdir: ~/backend/dist
  environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"



       #   export  TYPEORM_CONNECTION =postgres
  #   export  TYPEORM_MIGRATIONS_DIR =./src/migrations
  #   export  TYPEORM_MIGRATIONS=./src/migrations/*.ts
  #   export  TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
  #   export  TYPEORM_HOST=udapeople-db.cgkyxn12mkv9.us-east-1.rds.amazonaws.com
  #   export  TYPEORM_PORT=5432
  #   export  TYPEORM_USERNAME=postgres
  #   export  TYPEORM_PASSWORD=mypassword
  #   export  TYPEORM_DATABASE=postgres
  #   pm2 start main.js
  #   npm install
  #   pm2 stop default
  #   pm2 start npm -- start