version: 2.1
#  Define the jobs we want to run for this project
jobs:
   deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          command:
           destroy-environment 
           # Use the workflow id to mark your CloudFormation stacks so that you can reference them later on (ex: rollback). 
                      
workflows:
  cloud-front:
    jobs:
      - deploy-infrastructure