version: 2.1
#  Define the jobs we want to run for this project
jobs:
   cloudfront-update:
    docker:
      - image: amazon/aws-cli
    steps:
      - run: 
          name: create cloudfront
          command: 
            cd .circleci/files/
            --template-file cloudfront.yml \
            --stack-name InitialStack \
            --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
            --tags project=udapeople
workflows:
  cloud-front:
    jobs:
      - cloudfront-update