version: 2.1
#  Define the jobs we want to run for this project
jobs:
   configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["xoxb-3562588158196-3957099160115-lQi61hRT3zDDfQuELiFAigYO"] 
      - run:
          name: Install Ansible
          command: |
             apk add --update ansible
          
      - run:
          name: Run Playbook and Configure server
          command: ansible-playbook -i inventory.txt configure-server.yml
workflows:
  cloud-front:
    jobs:
      - configure_infrastructure