version: 2.1
#  Define the jobs we want to run for this project
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
           name: frontend
           command: npm install frontend 
  build-backend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout 
      - run: 
           name: backend
           command: npm install backend
  test-frontend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: 
           name: frontend
           command: npm install frontend test
  test-backend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: 
           name: backend
           command: npm install backend test
  scan-frontend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: 
           name: frontend
           command: npm install
  scan-backend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: 
           name: backend
           command: npm install
  deploy-cloudfront:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
           cd .circleci/files
           aws cloudformation deploy \
           --template-file cloudfront.yml \
           --stack-name InitialStack\
           --parameter-overrides WorkflowID=udapeople-kk1j287dhjppmz888
  deploy-infrastructure_backend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
           cd .circleci/files
           aws cloudformation deploy \
           --template-file backend.yml \
           --sack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
           --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
           --tags project=udapeople
           # Use the workflow id to mark your CloudFormation stacks so that you can reference them later on (ex: rollback). 
  deploy-infrastructure_frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: create infrastructure frontend
          command:
           cd .circleci/files
           aws cloudformation deploy \
           --template-file frontend.yml \
           --sack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
           --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
           --tags project=udapeople
           # Use the workflow id to mark your CloudFormation stacks so that you can reference them later on (ex: rollback). 
  
  Run_Playbook:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Run Playbook and Configure server
          command: cd .circleci/ansible
                   ansible-playbook -i inventory.txt configure-server.yml

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["7e:72:c0:23:ff:f3:1c:d9:4b:d7:82:73:89:65:e8:b3"]
      - run:
          name: Install dependencies
          command: |
             apk add --update ansible
  run-migrations:
    docker:
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - run:
          name: Run migrations
          command: |
                   cd backend
                   npm install
                   # Run and save the migration output
                   npm run migrations > migrations_dump.txt
  
  create_and_deploy_frontend:
    docker:
      - image: amazon/aws-cli
    steps:
       - checkout
       - run:
          name: Execute bucket.yml - Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
            --template-file bucket.yml \
            --stack-name stack-create-bucket-${CIRCLE_WORKFLOW_ID:0:7} \
            --parameter-overrides MyBucketName="mybucket-${CIRCLE_WORKFLOW_ID:0:7}"
       - run:
          name: Get backend url
          command: |
            # your code here
            export API_URL="http://3.90.4.11:3030"
            echo "API_URL = ${API_URL}"
            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
            cat frontend/.env
       - run:
           cd frontend
           npm install
           npm run build
           tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
           aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
  create_and_deploy_backend:
    docker:
      - image: amazon/aws-cli
    steps:
       - checkout
       - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["7e:72:c0:23:ff:f3:1c:d9:4b:d7:82:73:89:65:e8:b3"]
      
       - run:
           cd backend
           npm i
           npm run build
           cd .. tar -C backend -czvf artifact.tar.gz .
           cd .circleci/ansible
           echo "Contents  of the inventory.txt file is -------"
           cat inventory.txt
           ansible-playbook -i inventory.txt deploy-backend.yml
           npm install
           pm2 stop default
           pm2 start npm -- start
       - run:
           name: start app
           command: pm2 start main.js
           args:
             chdir:~/backend/dist
           environment:
              ENVIRONMENT: production
              TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
              TYPEORM_MIGRATIONS_DIR: "./migrations"
              TYPEORM_MIGRATIONS: "./migrations/*.js"
              TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
              TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
              TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
              TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
              TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
              TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

  
  backend_smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |
            export API_URL="http://3.82.214.177:3030"
            echo "${API_URL}"
            if curl "${API_URL}/api/status" | grep "ok"
            then
            return 0
            else
            return 1
            fi 
            - destroy_environment  
  frontend_smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |
           URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
           echo ${URL} 
           if curl -s ${URL} | grep "Welcome"
           then
           # Change this to 0 after the job fails
           return 0
           else
           return 1
           fi
           - destroy_environment  

  cloudfront-update:
    docker:
      - image: amazon/aws-cli
    steps:
      # Checkout code from git
      - run:
          name: Update cloudfront distribution
          command: |
            aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name InitialStack \
            --parameter-overrides WorkflowID=udapeople-kk1j287dhjppmz888 \
      # Here's where you will add some code to rollback on failure  
workflows:
  build_udapeople:
    jobs:
      #- build-frontend
      #- build-backend
      #- test-frontend:
      #   requires: [build-frontend]
      #- test-backend:
      #   requires: [build-backend] 
      #- scan-frontend:
      #   requires: [build-frontend]
      #- scan-backend:
      #   requires: [build-backend] 
      #- deploy-cloudfront
      #- deploy-infrastructure_backend
      #- deploy-infrastructure_frontend
      #- Run_Playbook
      #- configure_infrastructure
      #- run-migrations
      #- create_and_deploy_frontend
      - create_and_deploy_backend
      #- backend_smoke_test
      #- frontend_smoke_test
      #- cloudfront-update