version: 2.1
#  Define the jobs we want to run for this project
jobs:
 create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation describe-stack-events --stack-name myStack-24653
workflows:
  build_udapeople:
    jobs:
      - create_infrastructure 