version: 2.1
#  Define the jobs we want to run for this project
jobs:
   deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
           cd .circleci/files
           aws cloudformation deploy \
           --template-file cloudfront.yml \
           --stack-name InitialStack\
           --parameter-overrides WorkflowID=udapeople-kk1j287dhjppmz888
                      
workflows:
  cloud-front:
    jobs:
      - deploy-infrastructure