version: 2.1
#  Define the jobs we want to run for this project
jobs:
   run-migrations:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["xoxb-3562588158196-3957099160115-lQi61hRT3zDDfQuELiFAigYO"] 
      
      - run:
          name: Run migrations
          command: |
             cd backend/src
             npm install
             # Run and save the migration output
             npm run migrations > migrations_dump.txt
      - run:
          name: Send migration status to kvdb.io OR memstash.io
          command: |   
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
                then
               # If you are using memstash.io, generate the token "7933fe63-4687-4fa1-8426-aa25aa1730ec" on the website
                curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
               # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
                curl https://kvdb.io/9GE4jRtKznmVKRfvdBABBe/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1' fi
workflows:
  cloud-front:
    jobs:
      - run-migrations