version: 2.1
#  Define the jobs we want to run for this project
commands:
jobs:
  deploy-cloudfront:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
           cd .circleci/files
           aws cloudformation deploy \
           --template-file cloudfront.yml \
           --stack-name InitialStack\
           --parameter-overrides WorkflowID=udapeople-tt1j888madbein999
           
workflows:
  build_udapeople:
    jobs:
      - deploy-cloudfront
