version: 2.1
#  Define the jobs we want to run for this project
jobs:
   create_and_deploy_back_end:
    docker:
      - image: amazon/aws-cli
    steps:
       - checkout
       - run:
          name: deploy
          command: |
            npm i
            npm run build
            cd ..
            # Zip the directory
            tar -C backend -czvf artifact.tar.gz .
            cd .circleci/ansible
            echo "Contents  of the inventory.txt file is -------"
            cat inventory.txt
            ansible-playbook -i inventory.txt deploy-backend.yml

workflows:
  cloud-front:
    jobs:
      - create_and_deploy_back_end