version: 2.1
#  Define the jobs we want to run for this project
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              cd .circleci/files
              aws cloudformation deploy \
                --template-file cloudfront.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --parameter-overrides WorkflowID=udapeople-kk1j287dhjppmz888
                --region us-east-1
workflows:
  cloud-front:
    jobs:
      - create_infrastructure