version: 2.1
#  Define the jobs we want to run for this project
jobs:
 create_infrastructure_frontend: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file .circleci/files/frontend.yml \
                --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
                --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
                --tags project=udapeople
                --region us-east-1
workflows:
  build_udapeople:
    jobs:
      - create_infrastructure_frontend