version: 2.1
#  Define the jobs we want to run for this project
jobs:
   run-migrations:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["xoxb-3562588158196-3957099160115-lQi61hRT3zDDfQuELiFAigYO"] 
      
      - run:
          name: Run migrations
          command: |
             cd backend
             npm install
             # Run and save the migration output
             npm run migrations > migrations_dump.txt  
workflows:
  cloud-front:
    jobs:
      - run-migrations