version: 2.1
# Define the jobs we want to run for this project
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
           name: frontend
           command: cd frontend 
                    npm install 
                    npm run build
  build-backend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout 
      - run: 
           name: backend
           command: npm install BE
  test-frontend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: 
           name: frontend test
           command: npm test FE
  test-backend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: 
           name: backend test
           command: npm test BE
workflows:
  build_fb:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
         requires: [build-frontend]
      - test-backend:
         requires: [build-backend]