version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
           name: cd frontend
           command: 'npm install npm run build'
  build-backend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: 
           name: cd backend
           command: 'npm install npm run build'
  
  test-frontend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: 
           name: Run frontend test
           command: 'npm test FE'

  test-backend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: 
           name: Run backend test
           command: 'npm test BE'

workflows:
  build_and_fb:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
         requires: [build-frontend]
      - test-backend:
         requires: [build-backend]