version: 2.1
#  Define the jobs we want to run for this project
jobs:
   create_infrastructure:
     docker:
       - image: amazon/aws-cli
     steps:
      - checkout
      - run:
         name: Create Cloudformation
         command:
                aws cloudformation deploy \
                --template-file .circleci/files/backend.yml \
                --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
                --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
                --tags project=udapeople
           # Use the workflow id to mark your CloudFormation stacks so that you can reference them later on (ex: rollback). 
                      
workflows:
  cloud-front:
    jobs:
      - create_infrastructure 